version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    environment:
      POSTGRES_USER: ansk98
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ansk98_gnomepy

  client:
    container_name: gnomepy
    image: antonsk98/gnomepy:latest
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_USERNAME: "ansk98"
      DB_PASSWORD: "1234"
      DB_HOST: "postgres"
      BASE_URL: "http://localhost:5000"
